### ISSUE TITLE
UIImageView extention is required

### ISSUE THREAD

**Issue by redsubmarine** [MarioIannotta/LocalizedSwift#3]
Text using special fonts is sometimes treated as an image. `UIImageView extension` is required to use different images for different languages.

The usage should look like this:
```swift
@Localized("Image.Earth")
@IBOutlet private var imageView: UIImageView!
```

**Comment by MarioIannotta** [comment]
Released in 1.0.2 https://github.com/MarioIannotta/LocalizedSwift/releases/tag/1.0.2
